#!/usr/bin/ksh

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

# Copyright 2020 OmniOS Community Edition (OmniOSce) Association.

for mog in `find . -name \*.mog -o -name \*.p5m | cut -c3-`; do
	sh="`dirname $mog`/build.sh"
	PROG=xxx
	if [ -f "$sh" ]; then
		PROG=`nawk -F= '/^PROG=/ { print $2; exit }' $sh`
	fi
	sed < $mog '
		: loop
		/\\$/ {
			N
			s/\\\n//
			t loop
		}
	' | nawk -v prog=$PROG '
		function op(rid, rname) {
			split($0, a)
			for (i in a) {
				split(a[i], kv, /=/)
				if (kv[1] == rid)
					id = kv[2]
				else if (kv[1] == rname)
					name = kv[2]
			}
			print $1, id, name
		}
		{ gsub(/\$\(PROG\)/, prog) }
		$1 == "user" { op("uid", "username") }
		$1 == "group" { op("gid", "groupname") }
	'
done | sort -k 1,1 -k 2,2n

